TOTAL_USERS = 10

TOTAL_USERS.times do |n|
  # User.create()

  # rand(0..3).times do
  #   Listing.create(title: "#{Faker::Dessert.flavor} #{Faker::Dessert.variety}", artist: "#{Faker::Name.first_name} #{Faker::Name.last_name}", price: rand(1..100000), description: Faker::TvShows::TwinPeaks.quote, user_id: User.all[n].id)
  # end
end

# styles = [
#   'None',
#   'Miscellaneous',
#   'ASCII art',
#   'Abstract art',
#   'Art Brut',
#   'Abstract expressionism',
#   'Abstract illusionism',
#   'Academic art',
#   'Action painting',
#   'Aestheticism',
#   'Altermodern',
#   'American Barbizon school',
#   'American impressionism',
#   'American realism',
#   'American Scene Painting',
#   'Analytical art',
#   'Antipodeans',
#   'Arabesque',
#   'Arbeitsrat für Kunst',
#   'Art & Language',
#   'Art Deco',
#   'Art Informel',
#   'Art Nouveau',
#   'Art photography',
#   'Arte Povera',
#   'Arts and Crafts movement',
#   'Ashcan School',
#   'Assemblage',
#   'Les Automatistes',
#   'Auto-destructive art',
#   'Barbizon school',
#   'Baroque',
#   'Bauhaus',
#   'Black Arts Movement',
#   'Bengal School of Art',
#   'Classical Realism',
#   'Cloisonnism',
#   'COBRA',
#   'Color Field',
#   'Context art',
#   'Computer art',
#   'Concrete art',
#   'Conceptual art',
#   'Constructivism',
#   'Cubism',
#   'Cynical realism',
#   'Dada',
#   'Danube school',
#   'Dau-al-Set',
#   'De Stijl (also known as Neoplasticism)',
#   'Deconstructivism',
#   'Digital art',
#   'Ecological Art',
#   'Environmental art',
#   'Modern European ink painting',
#   'Excessivism',
#   'Expressionism',
#   'Fantastic realism',
#   'Fauvism',
#   'Feminist art',
#   'Figurative art',
#   'Figuration Libre',
#   'Fine Art',
#   'Folk art',
#   'Fluxus',
#   'Funk art',
#   'Futurism',
#   'Geometric abstract art',
#   'Graffiti/Street Art',
#   'Gutai group',
#   'Gothic art',
#   'Happening',
#   'Harlem Renaissance',
#   'Heidelberg School',
#   'Hudson River School',
#   'Hurufiyya',
#   'Hypermodernism',
#   'Hyperrealism',
#   'Impressionism',
#   'Interactive Art',
#   'Institutional critique',
#   'International Gothic',
#   'International Typographic Style',
#   'Kinetic art',
#   'Kinetic Pointillism',
#   'Kitsch movement',
#   'Land art',
#   'Les Nabis',
#   'Letterism',
#   'Light and Space',
#   'Lowbrow',
#   'Lyco art',
#   'Lyrical abstraction',
#   'Magic realism',
#   'Mannerism',
#   'Massurrealism',
#   'Maximalism',
#   'Metaphysical painting',
#   'Mingei',
#   'Minimalism',
#   'Modernism',
#   'Modular constructivism',
#   'Naive art',
#   'Neoclassicism',
#   'Neo-Dada',
#   'Neo-expressionism',
#   'Neo-figurative',
#   'Neoism',
#   'Neo-primitivism',
#   'Neo-romanticism',
#   'Net art',
#   'New Objectivity',
#   'New Sculpture',
#   'Northwest School',
#   'Nuclear art',
#   'Objective abstraction',
#   'Op Art',
#   'Orphism',
#   'Photorealism',
#   'Panfuturism',
#   'Pixel art',
#   'Plasticien',
#   'Plein Air',
#   'Pointillism',
#   'Pop art',
#   'Post-impressionism',
#   'Post-minimalism',
#   'Precisionism',
#   'Pre-Raphaelitism',
#   'Primitivism',
#   'Private Press',
#   'Process art',
#   'Psychedelic art',
#   'Purism',
#   'Qajar art',
#   'Quito School',
#   'Rasquache',
#   'Rayonism',
#   'Realism',
#   'Regionalism',
#   'Remodernism',
#   'Renaissance',
#   'Rococo',
#   'Romanesque',
#   'Romanticism',
#   'Samikshavad',
#   'Serial art',
#   'Shin hanga',
#   'Shock art',
#   'Sōsaku hanga',
#   'Socialist realism',
#   'Sots art',
#   'Space art',
#   'Street art',
#   'Stuckism',
#   'Sumatraism',
#   'Superflat',
#   'Suprematism',
#   'Surrealism',
#   'Symbolism',
#   'Synchromism',
#   'Synthetism',
#   'Tachisme (aka Informel)',
#   'Toyism',
#   'Transgressive art',
#   'Tonalism',
#   'Ukiyo-e',
#   'Underground comix',
#   'Unilalianism',
#   'Vancouver School',
#   'Vanitas',
#   'Verdadism',
#   'Video art',
#   'Visual Art',
#   'Viennese Actionism',
#   'Vorticism'
# ]

# styles.each do |style|
#   Style.create(name: style)
# end


